repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        args: ['--pytest-test-first']
    -   id: requirements-txt-fixer
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
    # Run the linter.
    -   id: ruff
        args: [  "--select", "I", "--fix" ]
        types_or: [ python, pyi, jupyter ]
    # Run the formatter.
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
