from setuptools import find_packages, setup

setup(
    name="IMLCV",
    author="Dvid Devoogdt",
    author_email="david.devoogdt@ugent.be",
    packages=find_packages(),
    install_requires=[
        "jax",
        "parsl",
        "keras",
        "yaff",
        "dill",
        "matplotlib",
        "numpy",
        "molmod",
        "scipy",
        "tensorflow",
        "jax_dataclasses",
        "optax",
        "flax",
        "umap",
        "h5py",
        "numba",
        "shapely",
        "alphashape",
        "ase",
        "pytest",
        "scikit-learn",
        "dill",
        "nyx",
        "filelock",
        "distrax",
        "jaxopt"
    ],
)
