from  IMLCV.base.rounds import run_md


rule run_md:
    input:  
        "{folder}/temp_{num}.in"
    output:
        "{folder}/temp_{num}.outr"
    run: for i in intput:
        with open(output[0], "w") as out:
                out.write(  "test"   )